version: "3.8"

services:
  backend:
    image: roxs33/xclone-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    image: roxs33/xclone-frontend:latest
    ports:
      - "3000:5173"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
