name: Build & Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/xclone-backend:${{ github.sha }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/xclone-frontend:${{ github.sha }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/xclone-app
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd ~/xclone-app

            curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml
            printf "%s\n" "${{ secrets.ENV_FILE }}" > .env 

            docker compose pull
            docker compose up -d
